// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKH-ihl4QU67ZrmkF2ujTbhEHk0dfPpQ0',
    appId: '1:977851540486:web:9529ab2d0c6e4c8e5fcf87',
    messagingSenderId: '977851540486',
    projectId: 'pet-care-7271c',
    authDomain: 'pet-care-7271c.firebaseapp.com',
    storageBucket: 'pet-care-7271c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtXd0fz1jgBjjx2QS4RVzHe6DhD_Yrxyk',
    appId: '1:977851540486:android:13670d88ab724f2b5fcf87',
    messagingSenderId: '977851540486',
    projectId: 'pet-care-7271c',
    storageBucket: 'pet-care-7271c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwU9tFSpsyWjNzJykj3UvU6XOsHx7PnCA',
    appId: '1:977851540486:ios:c7e328f97ad8fe755fcf87',
    messagingSenderId: '977851540486',
    projectId: 'pet-care-7271c',
    storageBucket: 'pet-care-7271c.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwU9tFSpsyWjNzJykj3UvU6XOsHx7PnCA',
    appId: '1:977851540486:ios:c7e328f97ad8fe755fcf87',
    messagingSenderId: '977851540486',
    projectId: 'pet-care-7271c',
    storageBucket: 'pet-care-7271c.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKH-ihl4QU67ZrmkF2ujTbhEHk0dfPpQ0',
    appId: '1:977851540486:web:991923f9944c34015fcf87',
    messagingSenderId: '977851540486',
    projectId: 'pet-care-7271c',
    authDomain: 'pet-care-7271c.firebaseapp.com',
    storageBucket: 'pet-care-7271c.appspot.com',
  );
}
